/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package menu;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import panelborder.EventMenuSelected;
import panelborder.modelmenu;
import tugas_akhir.halaman_awal;
import tugas_akhir.halaman_diagnosa;

/**
 *
 * @author mantaps
 */
public class menu extends javax.swing.JPanel {

    /**
     * Creates new form menu
     */
    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected event) {
        this.event = event;
        listMenu2.addEventMenuSelected(event);
    }
    
    public menu() {
        initComponents();
        setOpaque(false);
        listMenu2.setOpaque(false);
        init();
    }
    
    private void init() {
        listMenu2.addItem(new modelmenu("Pilih Gejala", modelmenu.MenuType.MENU));
        listMenu2.addItem(new modelmenu("Data Gejala", modelmenu.MenuType.MENU));
        listMenu2.addItem(new modelmenu("Data kerusakan", modelmenu.MenuType.MENU));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listMenu2 = new panelborder.ListMenu();
        halaman_awal = new javax.swing.JButton();

        halaman_awal.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        halaman_awal.setText("Halaman Awal");
        halaman_awal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        halaman_awal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halaman_awalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(halaman_awal, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(halaman_awal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void halaman_awalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halaman_awalActionPerformed
        // TODO add your handling code here:
        halaman_awal f2 = new halaman_awal();
        f2.show();
        
        halaman_diagnosa parent = (halaman_diagnosa) this.getTopLevelAncestor();
        parent.dispose();
        //dispose();
    }//GEN-LAST:event_halaman_awalActionPerformed
        
    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#2980b9"), 0, getHeight(), Color.decode("#2c3e50"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton halaman_awal;
    private panelborder.ListMenu listMenu2;
    // End of variables declaration//GEN-END:variables

    


    
}
